version: '3.4'
services:
  app:
    build:
      context: .
    container_name: deg_deg
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DOCKER_DATABASE_URL}
    ports:
      - "${APPLICATION_PORT}:${APPLICATION_PORT}"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/dist
      - /usr/src/app/node_modules
